Init for Sphinx docs system (#22)
* Init for Sphinx docs system

* Docs skeletons

* Turn warnings into errors when building docs with Sphinx

* Fix docs build target

* Now using Sphinx's autodocs

* Add items from airgun.entities and airgun.views

* Move instructions to build docs into separate file and out of main README

* Fix typo in the docs

* Move individual entities docs out of speparate files into central one

* Naiive attempt to implement Travis check for docs sanity check

* OK, that would require to install all the libs. Lets try with setup.py

* Travis job fails. Maybe distutils and setuptools versions?

See https://stackoverflow.com/questions/21136266/typeerror-dist-must-be-a-distribution-instance-when-resolving-beautifulsoup-d

Traceback was:

    Searching for wait_for
    Reading https://pypi.python.org/simple/wait_for/
    Downloading https://pypi.python.org/packages/ec/4e/bf68e38c5e149a69ee156b9eeb68409a6b72895717343831b164b663c6c2/wait_for-1.0.9.tar.gz#md5=306d365681e7c30157986981e9eb3363
    Best match: wait-for 1.0.9
    Processing wait_for-1.0.9.tar.gz
    Writing /tmp/easy_install-a_j69mdc/wait_for-1.0.9/setup.cfg
    Running wait_for-1.0.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-a_j69mdc/wait_for-1.0.9/egg-dist-tmp-tc0qgdx0
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pbr/util.py", line 251, in cfg_to_args
        kwargs = setup_cfg_to_setup_kwargs(config, script_args)
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pbr/util.py", line 385, in setup_cfg_to_setup_kwargs
        cmd = cls(dist)
      File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/setuptools/__init__.py", line 147, in __init__
        _Command.__init__(self, dist)
      File "/opt/python/3.6.3/lib/python3.6/distutils/cmd.py", line 57, in __init__
        raise TypeError("dist must be a Distribution instance")
    TypeError: dist must be a Distribution instance
    error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-a_j69mdc/wait_for-1.0.9/setup.cfg: TypeError: dist must be a Distribution instance

* Suggested by abalakht

* Now return back pip install sphinx :)

* Also add Sphinx requirement into the docs

* Added sphinx.ext.intersphinx and python intersphinx_mapping

* Fixed typo in the docstring

* Move additional requirements into requirements-optional.txt

* Flake8

* Fixing typo in Andrii's name. Sorry for that :-/